### ISSUE TITLE
Details about experiments on the toy datasets.

### ISSUE THREAD

**Issue by jian-liang** [JingWang18/Discriminative-Feature-Alignment#1]
Nice work! Would you like to share the codes for the toy experiments? Thanks!

**Comment by JingWang18** [comment]
Thank you so much for your interest in our work! I will share the codes for the toy experiments tomorrow and let you know once the code is uploaded on Github.

**Comment by jian-liang** [comment]
> Thank you so much for your interest in our work! I will share the codes for the toy experiments tomorrow and let you know once the code is uploaded on Github.

Thanks!

**Comment by JingWang18** [comment]
> Nice work! Would you like to share the codes for the toy experiments? Thanks!

Hi, 

Our lab building is locked due to COVID-19. I just send an application for accessing our lab to our department. I will upload the code as soon as I get access to our lab. My great apologies for such a delay.

**Comment by JingWang18** [comment]
> > Thank you so much for your interest in our work! I will share the codes for the toy experiments tomorrow and let you know once the code is uploaded on Github.
> 
> Thanks!

Hi,

The codes for the toy experiments have been uploaded under the "Synthetic Experiments" folder. Please let me know if you have any questions or you find any mistakes in the code implementation.

Cheers,
Jing

**Comment by jian-liang** [comment]
> > > Thank you so much for your interest in our work! I will share the codes for the toy experiments tomorrow and let you know once the code is uploaded on Github.
> > 
> > 
> > Thanks!
> 
> Hi,
> 
> The codes for the toy experiments have been uploaded under the "Synthetic Experiments" folder. Please let me know if you have any questions or you find any mistakes in the code implementation.
> 
> Cheers,
> Jing

Thanks, JIng!
