### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by inspire-lts** [JingWang18/Discriminative-Feature-Alignment#3]
Hi,I would like to know how to do the visualization by t-sne in the paper. Could you please share the code? Thank you very much!
![](https://gitee.com/new_lts/MyImages/raw/master/img/20201220163023.png)

**Comment by JingWang18** [comment]
Hi you can find more information regarding how to implement t-sne visualization on https://lvdmaaten.github.io/tsne/

For more details on t-sne, please refer to its original paper “Visualizing Data using t-SNE”
